version: '3.6'

services:
  web:
    build: ./src
    restart: always
    command: uwsgi --http :80 --module srv.web:app --workers 1 --threads 1
    volumes:
      - ./src:/srv:delegated
    ports:
      - 80:80