version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.14.0
  aws-ecs: circleci/aws-ecs@1.4.0
  terraform: circleci/terraform@1.1.0


# AWS_ACCOUNT_ID
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY

# AWS_REGION – eu-north-1
# AWS_ECR_REPOSITORY_NAME – ecr_playground_repo
# AWS_ECS_TASK_NAME – ecs_playground_task_web, ecs_playground_task_celery
# AWS_ECS_SERVICE_NAME – ecs_playground_service_web, ecs_playground_service_celery
# AWS_ECS_CLUSTER_NAME – ecs_playground_cluster


#orbs:
#  aws-ecr: circleci/aws-ecr@0.0.2
#  aws-ecs: circleci/aws-ecs@0.0.10

jobs:
  terraform-update-infrastructure:
    docker:
      - image: hashicorp/terraform:light

    steps:
      - checkout
      - run:
          name: Terraform init & apply
          command: |
            cd terraform-playground
            terraform init -backend-config="access_key=${AWS_ACCESS_KEY_ID}" -backend-config="secret_key=${AWS_SECRET_ACCESS_KEY}"
            source setup_env.sh
            terraform plan
            terraform apply -auto-approve

workflows:
  build-and-deploy:
    jobs:
      - terraform-update-infrastructure

      - aws-ecr/build-and-push-image:
          repo: "${AWS_ECR_REPOSITORY_NAME}"
          skip-when-tags-exist: false
          tag: "latest,${CIRCLE_SHA1}"
          path: src
          create-repo: true

      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
            - terraform-update-infrastructure

          aws-region: ${AWS_REGION}

          family: "${AWS_ECS_SERVICE_NAME}"
          cluster-name: "${AWS_ECS_CLUSTER_NAME}"
          service-name: "${AWS_ECS_SERVICE_NAME}"
          container-image-name-updates: "container=${AWS_ECR_REPOSITORY_NAME},tag=${CIRCLE_SHA1}"
